# Tensorflow Basics

In [ ]:
import tensorflow as tf

/Users/andrewlou/Documents/Coding/NYU-Machine-Learning/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [ ]:
# Tensors
a = tf.constant([1, 2, 3])
b = tf.constant([3, 2, 1])

In [3]:
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
# Point wise operations (addition)
c = a + b

print(c)

tf.Tensor([4 4 4], shape=(3,), dtype=int32)


In [ ]:
# Tensor reshaping
c = tf.reshape(c, (-1, 1))

print(c)

tf.Tensor(
[[4]
 [4]
 [4]], shape=(3, 1), dtype=int32)


In [ ]:
# Numpy array conversion
numpy_c = c.numpy()

print(numpy_c)
print(type(numpy_c))

[[4]
 [4]
 [4]]
<class 'numpy.ndarray'>


In [15]:
# Matrices
matrix_a = tf.constant([[1, 2, 3],
                       [4, 5, 6]])

print(matrix_a)
print(matrix_a.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)


In [16]:
# Floats
matrix_b = tf.constant([[1.3, 2.1, 3.6],
                       [4.4, 5.7, 6.5]])

print(matrix_b)
print(matrix_b.shape)

tf.Tensor(
[[1.3 2.1 3.6]
 [4.4 5.7 6.5]], shape=(2, 3), dtype=float32)
(2, 3)


In [19]:
# Tensor operations MUST be the same data type
matrix_c = tf.cast(matrix_a, 'float32') + matrix_b

print(matrix_c)

tf.Tensor(
[[ 2.3  4.1  6.6]
 [ 8.4 10.7 12.5]], shape=(2, 3), dtype=float32)


In [31]:
# Specifying data types
x = tf.constant([1, 2, 3, 4, 5], dtype=float)
print(x)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [32]:
y = tf.constant([3, 5, 7, 9, 11], dtype=float)
print(y)

tf.Tensor([ 3.  5.  7.  9. 11.], shape=(5,), dtype=float32)


## Building a simple Neural Net

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Create model
model = Sequential([
    Dense(1, activation='relu', input_shape=[1])
])

/Users/andrewlou/Documents/Coding/NYU-Machine-Learning/.venv/lib/python3.9/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
# You must compile the model after setting up the network
model.compile(
    optimizer='sgd',
    loss='mean_squared_error'
)

In [33]:
model.fit(x, y, epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 57.0000
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 57.0000
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 57.0000
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 57.0000
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 57.0000
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 57.0000
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 57.0000
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 57.0000
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 57.0000
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 57.0000
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 57.0000
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 57.0000
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 57.0000
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 57.0000
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 57.0000
Epoc